In [6]:
%run ./footprint_v_biocapacity.ipynb 

eco_sort.head()

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Data Quality,Deficit or Reserve %
0,Singapore,Asia-Pacific,5.30,0.91,"$53,122.40",0.67,0.24,0.91,5.91,0.22,...,0.00,0.00,0.01,0.03,0.05,-7.92,4.61,159.47,5,-15840.000000
1,Bermuda,North America,0.06,NaN,"$70,626.30",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.13,-5.64,3.33,44.05,3T,-4338.461538
2,Barbados,Latin America,0.28,0.79,"$15,722.80",0.56,0.24,0.14,3.28,0.22,...,0.00,0.02,0.04,0.04,0.19,-4.29,2.58,23.79,5,-2257.894737
3,Aruba,Latin America,0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.57,-11.31,6.86,20.69,2,-1984.210526
4,Réunion,Africa,0.86,NaN,NaN,0.14,0.01,0.15,3.27,0.09,...,0.01,0.04,0.00,0.00,0.18,-3.47,2.11,20.18,5,-1927.777778